### ISSUE TITLE
[BUG] `bpf-loader-rs` and `ecli` build failed on aarch64-linux

### ISSUE THREAD

**Issue by oluceps** [eunomia-bpf/eunomia-bpf#276] opened 2023-06-29 19:08 UTC
**Describe the bug**

As in the title.
Occurs on both latest release `v0.3.55` and 1976dda760a2dead485a2d5fe29ece9cf0692254.

Also affects `ecli`.

**To Reproduce**
Enter `bpf-loader-rs` directory and build:
```text
user@opulr-aarch64 ~/e/bpf-loader-rs ((v0.3.55))> cargo b
   Compiling bpf-loader-lib v0.1.6 (/home/user/eunomia-bpf/bpf-loader-rs/bpf-loader-lib)
error[E0308]: mismatched types
   --> bpf-loader-lib/src/skeleton/builder.rs:114:41
    |
114 |               open_bpts.btf_custom_path = path_holder
    |  _____________-------------------------___^
    | |             |
    | |             expected due to the type of this binding
115 | |                 .as_ref()
116 | |                 .unwrap()
117 | |                 .as_os_str()
118 | |                 .as_bytes()
119 | |                 .as_ptr() as *const i8;
    | |______________________________________^ expected `*const u8`, found `*const i8`
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*const i8`

error[E0308]: mismatched types
   --> bpf-loader-lib/src/skeleton/builder.rs:122:41
    |
122 |             open_bpts.btf_custom_path = env_btf.as_bytes().as_ptr() as *const i8;
    |             -------------------------   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `*const u8`, found `*const i8`
    |             |
    |             expected due to the type of this binding
    |
    = note: expected raw pointer `*const u8`
               found raw pointer `*const i8`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `bpf-loader-lib` (lib) due to 2 previous errors
```

**Expected behavior**
Successful build.

**Desktop (please complete the following information):**
```
NAME="openEuler"
VERSION="22.03 (LTS-SP1)"
ID="openEuler"
VERSION_ID="22.03"
PRETTY_NAME="openEuler 22.03 (LTS-SP1)"
ANSI_COLOR="0;31"
```

```
cargo --version
cargo 1.70.0 (ec8a8a0ca 2023-04-25)
```

```
uname -r
5.10.0-136.22.0.98.oe2203sp1.aarch64
```

**Comment by Officeyutong** [comment] 2023-07-05 09:47
Seems caused by the underlying type of c_char. I'll fix this

**Comment by Officeyutong** [comment] 2023-07-09 08:38
Fixed by https://github.com/eunomia-bpf/eunomia-bpf/pull/280

**Closed** 2023-07-09 08:37 UTC
Labels: bug
